### ISSUE TITLE
What will happen if RM crash

### ISSUE THREAD

**Issue by ardhipoetra** [ardhipoetra/vgridscheduler-python#14]
Just wondering. 

My idea is to just let it down, GS will know it anyway. Then after it restarts, GS will re-run the job assigned to that RM (or maybe run the job to another RM)

_Assumption : just 1 RM per cluster_

**Comment by sudeshm** [comment]
I am OK with one RM per cluster 

Even if we do not want to do anything when RM crash There should be some way that GS know about its failure so that it wont consider it when scheduling the job ??? 

But what happen to the jobs which were running during the time of crash ??  They should be restarted again on some other cluster ??? This information is required ??? Otherwise we are loosing the that percentage of jobs from the system .
