### ISSUE TITLE
STATUS 

### ISSUE THREAD

**Issue by sudeshm** [ardhipoetra/vgridscheduler-python#27]
_chooseRM is now implemented and sucessful  and avilable on my branch

added thre new api called get_workloadRM in the resource manager class which is yet to be implemented . we need to have the gs and rm status structure/variable in place so that we can start implementing these apis 

Next I will start with the _monitorRM and then _monitorGS may be ... 

One more thing .. when you exit the program it is crashes as you decribed earlier ... this makes the name server crash everytime and difficult to test the program .. it consume lot of time to test this function chooseRM 

Can you please fix this as a first priority ?

**Comment by ardhipoetra** [comment]
The structure for GS and RM already in the master and/or dev branch since 2 days ago. 

About the issue when exit the program, it can't be helped. You can exit the program in the right way by inputting '0'. But if you code something that broke the flow, it may exit prematurely. The problem mainly happen on _locking socket_. I will try to find out how to unlock those socket manually.

**Comment by sudeshm** [comment]
I was refering the the the state vaibles and not the overall structure of GM and RM.

like .. what structure should be written when GS ask for the RM state ...

what variables should be available in each class to give the right information about  RM and GS to each other for consistency/replication. 

Regarding the crash part I got the erros when I exit with 0 also . have you include new patch ?
